# Generated by Django 3.2.4 on 2024-07-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_items_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ecommerce/pimg')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
